In [13]:
import pulp
import numpy as np


def farm_program(costs, max_farm, max_area):
		row = len(costs)
		col = len(costs[0])
		prob = pulp.LpProblem('Farm', sense= pulp.LpMaximize)
		var = [[pulp.LpVariable(f'x{i}{j}',lowBound=0) for j in range(col)]
						for i in range(row)] 
		flatten = lambda x:[y for l in x for y in flatten(l)] if type(x) is list else [x]
		prob +=pulp.lpDot(flatten(var), costs.flatten())
		for i in range(row):
				prob += pulp.lpSum(var[i]) <= max_farm[i]
		for j in range(col):
				prob += pulp.lpSum(var[i][j] for i in range(row)) <= max_area[j] 
		prob.solve()
		print('target', pulp.value(prob.objective))
		print('varialbe', [[pulp.value(var[i][j]) for j in range(col)] for i in range(row)])
costs = np.array([ [500,550,630,1000,800,700],
					[800,700,600,950,900,930],
					[1000,960,840,650,600,700],
					[1200,1040,980,860,880,780]])

print(costs)

max_farm = [76,88,96,40]
max_area = [42,56,44,39,60,59]

result = farm_program(costs, max_farm, max_area)

[[ 500  550  630 1000  800  700]
 [ 800  700  600  950  900  930]
 [1000  960  840  650  600  700]
 [1200 1040  980  860  880  780]]
target 284230.0
varialbe [[0.0, 0.0, 6.0, 39.0, 31.0, 0.0], [0.0, 0.0, 0.0, 0.0, 29.0, 59.0], [2.0, 56.0, 38.0, 0.0, 0.0, 0.0], [40.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
